# Generated by Django 4.0.3 on 2022-07-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('ufile', models.FileField(upload_to='Files/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
